// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MetricsCollector is an autogenerated mock type for the MetricsCollector type
type MetricsCollector struct {
	mock.Mock
}

// IncPVZCreated provides a mock function with no fields
func (_m *MetricsCollector) IncPVZCreated() {
	_m.Called()
}

// IncProductsAdded provides a mock function with no fields
func (_m *MetricsCollector) IncProductsAdded() {
	_m.Called()
}

// IncReceptionsCreated provides a mock function with no fields
func (_m *MetricsCollector) IncReceptionsCreated() {
	_m.Called()
}

// IncRequestsTotal provides a mock function with given fields: method, path, statusCode
func (_m *MetricsCollector) IncRequestsTotal(method string, path string, statusCode string) {
	_m.Called(method, path, statusCode)
}

// ObserveRequestDuration provides a mock function with given fields: method, path, duration
func (_m *MetricsCollector) ObserveRequestDuration(method string, path string, duration float64) {
	_m.Called(method, path, duration)
}

// NewMetricsCollector creates a new instance of MetricsCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsCollector {
	mock := &MetricsCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
