// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pvz_v1 "pvz-service-avito-internship/pkg/grpc/pvz/v1"
)

// PVZServiceClient is an autogenerated mock type for the PVZServiceClient type
type PVZServiceClient struct {
	mock.Mock
}

// GetPVZList provides a mock function with given fields: ctx, in, opts
func (_m *PVZServiceClient) GetPVZList(ctx context.Context, in *pvz_v1.GetPVZListRequest, opts ...grpc.CallOption) (*pvz_v1.GetPVZListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetPVZList")
	}

	var r0 *pvz_v1.GetPVZListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pvz_v1.GetPVZListRequest, ...grpc.CallOption) (*pvz_v1.GetPVZListResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pvz_v1.GetPVZListRequest, ...grpc.CallOption) *pvz_v1.GetPVZListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pvz_v1.GetPVZListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pvz_v1.GetPVZListRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPVZServiceClient creates a new instance of PVZServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPVZServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PVZServiceClient {
	mock := &PVZServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
