// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	pvz_v1 "pvz-service-avito-internship/pkg/grpc/pvz/v1"

	mock "github.com/stretchr/testify/mock"
)

// PVZServiceServer is an autogenerated mock type for the PVZServiceServer type
type PVZServiceServer struct {
	mock.Mock
}

// GetPVZList provides a mock function with given fields: _a0, _a1
func (_m *PVZServiceServer) GetPVZList(_a0 context.Context, _a1 *pvz_v1.GetPVZListRequest) (*pvz_v1.GetPVZListResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetPVZList")
	}

	var r0 *pvz_v1.GetPVZListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pvz_v1.GetPVZListRequest) (*pvz_v1.GetPVZListResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pvz_v1.GetPVZListRequest) *pvz_v1.GetPVZListResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pvz_v1.GetPVZListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pvz_v1.GetPVZListRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedPVZServiceServer provides a mock function with no fields
func (_m *PVZServiceServer) mustEmbedUnimplementedPVZServiceServer() {
	_m.Called()
}

// NewPVZServiceServer creates a new instance of PVZServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPVZServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *PVZServiceServer {
	mock := &PVZServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
