http:
  port: "8080"

grpc:
  port: "3000"

metrics:
  port: "9000"

database:
  host: "localhost"
  port: "5432"
  user: "user"
  password: "password"
  name: "pvz_db"
  ssl_mode: "disable"

auth:
  jwt_secret: "your_jwt_secret"
  jwt_ttl_hours: 2h

logger:
  level: "info"

hasher:
  bcrypt_cost: 10

test_database:
  host: "localhost"
  port: "5432"
  user: "test"
  password: "test_password"
  name: "test_db"
  ssl_mode: "disable"